In [10]:
import os
import re
import pandas as pd

import sys
sys.path.append('E:/Code/chat/gdpr')

from regulations_rag.standard_regulation_index import load_parquet_data, save_parquet_data
key = os.getenv('encryption_key_gdpr')

from openai import OpenAI
openai_client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"),)

model = "text-embedding-3-large"
dimensions = 1024

In [18]:
file = "../inputs/index/dpo.parquet"
index = load_parquet_data(file, key)

# for index, row in gdpr_index[gdpr_index['section_reference'].str.startswith('25')].iterrows():
#     print(f"-- {row['text']}")

# for index, row in gdpr_index.iterrows():
#     if 'location' in row['text'].lower():
#         print(f"* {row['text']}")

### Add to an existing index

In [20]:
import importlib
import src.index_tools
importlib.reload(src.index_tools)
from src.index_tools import add_to_index

text = "what is a dpo?"
section_reference = "1"
source = "question"
document = "DPO"

index = add_to_index(openai_client, index_df = index, text = text, section_reference = section_reference, source = source, document = document, embedding_model = model, embedding_dimensions = dimensions)

In [21]:
save_parquet_data(index, file, key)

In [22]:
index[index["section_reference"] == '1']

,section_reference,text,source,embedding,document
0,1,The General Data Protection Regulation (GDPR) ...,summary,"[-0.09357940405607224, -0.015285134315490723, ...",DPO
35,1,Who needs to appoint a Data Protection Officer...,question,"[-0.06357274204492569, -0.019091403111815453, ...",DPO
36,1,What is the function of a Data Protection Offi...,question,"[-0.09614308178424835, -0.03115009143948555, -...",DPO
37,1,What responsibilities do controllers and proce...,question,"[-0.033698320388793945, -0.0370718389749527, -...",DPO
38,1,Can a Data Protection Officer (DPO) be held pe...,question,"[-0.08404096961021423, -0.05464310944080353, -...",DPO
117,1,what is a dpo?,question,"[-0.038724202662706375, -0.030565690249204636,...",DPO

### Change an existing index (not checked yet)

In [54]:
from src.index_tools import update_text_in_index, add_to_index

text_to_change = "What points need to be addressed in the Binding Corporate Rules for Controllers (BCR-C)"
changed_text = "What points need to be addressed in the Binding Corporate Rules for controllers?"
embedding_model = model
embedding_dimensions = dimensions

index_df = update_text_in_index(openai_client = openai_client, index_df = index, text_to_change = text_to_change, changed_text = changed_text, embedding_model = embedding_model, embedding_dimensions = embedding_dimensions)

,section_reference,text,source,embedding,document
0,1.1,You can use binding corporate rules (BCRs) for...,summary,"[-0.009783994406461716, -0.06066862493753433, ...",Article_47_BCR
1,1.5,Binding Corporate Rules for controllers (BCR-C...,summary,"[-0.017316676676273346, -0.021807707846164703,...",Article_47_BCR
2,1.6,You must comply with EU data protection legisl...,summary,"[-0.07271231710910797, -0.06814079731702805, -...",Article_47_BCR
3,1.7,You must use Binding Corporate Rules (BCR) as ...,summary,"[-0.017403494566679, -0.08751912415027618, -0....",Article_47_BCR
4,1.8,Binding Corporate Rules (BCRs) need approval f...,summary,"[-0.004610632546246052, -0.043068330734968185,...",Article_47_BCR
...,...,...,...,...,...
82,3.6,What agreements must be made regarding the han...,question,"[-0.04174955189228058, -0.0986546203494072, -0...",Article_47_BCR
83,3.7,What expectations are set for members of Bindi...,question,"[-0.04039411619305611, -0.08921048790216446, -...",Article_47_BCR
84,3.8,What obligations are there to keep Binding Cor...,question,"[-0.04588606581091881, -0.06260394304990768, -...",Article_47_BCR
85,3.9,What definitions must be included in the Bindi...,question,"[-0.010924087837338448, -0.03873256593942642, ...",Article_47_BCR
86,Analysis,What points need to be addressed in the Bindin...,question,"[-0.0038541764952242374, -0.05298667028546333,...",Article_47_BCR

### Delete an index (not checked yet)

In [84]:
from src.index_tools import remove_from_index

text_to_delete = "What happens if local laws conflict with the standards of binding corporate rules?"
article_47_index = remove_from_index(article_47_index, text_to_delete)

In [30]:
save_parquet_data(index_df, "../inputs/index/gdpr.parquet", key)

In [31]:
index_df[index_df['document'] == "article_30_5"]

,text,embedding,source,section_reference,document
147,Under what conditions could you be exempt from...,"[-0.03439036011695862, -0.0008122794097289443,...",question,all,article_30_5

In [9]:
import os
from regulations_rag.standard_regulation_index import load_parquet_data, save_parquet_data
key = os.getenv('encryption_key_gdpr')

path_to_file = "../inputs/index/article_30_5.parquet"
index = load_parquet_data(path_to_file, key)

In [10]:
#index["document"] = "Article_30_5"
index

  section_reference  ...      document
0               all  ...  Article_30_5
1               all  ...  Article_30_5
2               all  ...  Article_30_5
3               all  ...  Article_30_5
4               all  ...  Article_30_5
5               all  ...  Article_30_5
6               all  ...  Article_30_5
7               all  ...  Article_30_5

[8 rows x 5 columns]

In [ ]:
save_parquet_data(index, file, key)